name: Deploy React App
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
<<<<<<< HEAD
        node-version: [10.x]
=======
        node-version: [12.x]
>>>>>>> props-and-state
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Deploy to GH Pages
      run: |
        git config --global user.name "${{ github.actor }}"
        git remote set-url origin https://${{ secrets.PERSONAL_SECRET }}@github.com/${{ github.repository }}.git
        npm install
<<<<<<< HEAD
        npm run deploy
=======
        npm run deploy
>>>>>>> props-and-state
